import 'package:flutter/material.dart';

import '../../../../core/constants/app_colors.dart';

class StudentNotificationsSheet extends StatefulWidget {
  final VoidCallback? onAllRead;

  const StudentNotificationsSheet({super.key, this.onAllRead});

  @override
  State<StudentNotificationsSheet> createState() =>
      _StudentNotificationsSheetState();
}

class _NotificationItemData {
  final String id;
  final IconData icon;
  final Color iconColor;
  final String title;
  final String description;
  final String time;
  bool isUnread;

  _NotificationItemData({
    required this.id,
    required this.icon,
    required this.iconColor,
    required this.title,
    required this.description,
    required this.time,
    this.isUnread = true,
  });
}

class _StudentNotificationsSheetState extends State<StudentNotificationsSheet> {
  final List<_NotificationItemData> _notifications = [
    _NotificationItemData(
      id: '1',
      icon: Icons.local_fire_department_rounded,
      iconColor: AppColors.secondary,
      title: '7-Day Streak Active! 🔥',
      description:
          'Complete today\'s study goal before midnight to keep your streak burning.',
      time: '1 hour ago',
      isUnread: true,
    ),
    _NotificationItemData(
      id: '2',
      icon: Icons.auto_awesome_rounded,
      iconColor: AppColors.primary,
      title: 'Daily AI Quiz is Ready',
      description:
          '5 new questions generated by EduSpark are waiting for you in Science.',
      time: '3 hours ago',
      isUnread: true,
    ),
    _NotificationItemData(
      id: '3',
      icon: Icons.emoji_events_rounded,
      iconColor: AppColors.secondary,
      title: 'Badge Unlocked: Quiz Whiz! 🏆',
      description:
          'You scored 100% on the Maths Basics quiz and earned +50 XP bonus.',
      time: 'Yesterday',
      isUnread: false,
    ),
    _NotificationItemData(
      id: '4',
      icon: Icons.note_alt_rounded,
      iconColor: AppColors.success,
      title: 'Revision Notes Ready',
      description:
          'Your quick revision notes for Photosynthesis have been generated.',
      time: '2 days ago',
      isUnread: false,
    ),
    _NotificationItemData(
      id: '5',
      icon: Icons.campaign_rounded,
      iconColor: AppColors.primary,
      title: 'Teacher Announcement 📢',
      description:
          'Ms. Sharma uploaded new practice problems on Linear Equations.',
      time: '3 days ago',
      isUnread: false,
    ),
  ];

  @override
  Widget build(BuildContext context) {
    final unreadCount = _notifications.where((n) => n.isUnread).length;

    return Container(
      height: MediaQuery.of(context).size.height * 0.82,
      decoration: const BoxDecoration(
        color: AppColors.background,
        borderRadius: BorderRadius.vertical(top: Radius.circular(28)),
      ),
      child: SafeArea(
        top: false,
        child: Column(
          children: [
            const SizedBox(height: 12),
            Container(
              width: 42,
              height: 5,
              decoration: BoxDecoration(
                color: AppColors.border,
                borderRadius: BorderRadius.circular(10),
              ),
            ),
            const SizedBox(height: 16),
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 20),
              child: Row(
                children: [
                  const Text(
                    'Notifications',
                    style: TextStyle(
                      color: AppColors.textPrimary,
                      fontSize: 20,
                      fontWeight: FontWeight.w800,
                    ),
                  ),
                  const SizedBox(width: 8),
                  if (unreadCount > 0)
                    Container(
                      padding: const EdgeInsets.symmetric(
                        horizontal: 8,
                        vertical: 3,
                      ),
                      decoration: BoxDecoration(
                        color: AppColors.primary,
                        borderRadius: BorderRadius.circular(10),
                      ),
                      child: Text(
                        '$unreadCount New',
                        style: const TextStyle(
                          color: Colors.white,
                          fontSize: 11,
                          fontWeight: FontWeight.w700,
                        ),
                      ),
                    ),
                  const Spacer(),
                  if (unreadCount > 0)
                    TextButton(
                      onPressed: () {
                        setState(() {
                          for (var n in _notifications) {
                            n.isUnread = false;
                          }
                        });
                        widget.onAllRead?.call();
                      },
                      child: const Text(
                        'Mark all read',
                        style: TextStyle(
                          color: AppColors.primary,
                          fontWeight: FontWeight.w700,
                          fontSize: 13,
                        ),
                      ),
                    ),
                  IconButton(
                    onPressed: () => Navigator.of(context).pop(),
                    icon: const Icon(
                      Icons.close_rounded,
                      color: AppColors.textSecondary,
                    ),
                  ),
                ],
              ),
            ),
            const SizedBox(height: 10),
            Expanded(
              child: _notifications.isEmpty
                  ? const Center(
                      child: Text(
                        'No notifications right now',
                        style: TextStyle(color: AppColors.textSecondary),
                      ),
                    )
                  : ListView.separated(
                      padding: const EdgeInsets.fromLTRB(20, 4, 20, 25),
                      physics: const BouncingScrollPhysics(),
                      itemCount: _notifications.length,
                      separatorBuilder: (_, _) => const SizedBox(height: 12),
                      itemBuilder: (context, index) {
                        final item = _notifications[index];
                        return InkWell(
                          onTap: () {
                            setState(() {
                              item.isUnread = false;
                            });
                          },
                          borderRadius: BorderRadius.circular(18),
                          child: Container(
                            padding: const EdgeInsets.all(16),
                            decoration: BoxDecoration(
                              color: item.isUnread
                                  ? AppColors.surfaceLight
                                  : AppColors.surface,
                              borderRadius: BorderRadius.circular(18),
                              border: Border.all(
                                color: item.isUnread
                                    ? AppColors.primary.withValues(alpha: 0.3)
                                    : AppColors.border,
                              ),
                            ),
                            child: Row(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Container(
                                  width: 44,
                                  height: 44,
                                  decoration: BoxDecoration(
                                    color: item.iconColor.withValues(alpha: 0.12),
                                    borderRadius: BorderRadius.circular(14),
                                  ),
                                  child: Icon(
                                    item.icon,
                                    color: item.iconColor,
                                    size: 22,
                                  ),
                                ),
                                const SizedBox(width: 14),
                                Expanded(
                                  child: Column(
                                    crossAxisAlignment:
                                        CrossAxisAlignment.start,
                                    children: [
                                      Row(
                                        mainAxisAlignment:
                                            MainAxisAlignment.spaceBetween,
                                        children: [
                                          Expanded(
                                            child: Text(
                                              item.title,
                                              style: TextStyle(
                                                color: AppColors.textPrimary,
                                                fontSize: 14.5,
                                                fontWeight: item.isUnread
                                                    ? FontWeight.w800
                                                    : FontWeight.w600,
                                              ),
                                            ),
                                          ),
                                          if (item.isUnread)
                                            Container(
                                              width: 8,
                                              height: 8,
                                              decoration: const BoxDecoration(
                                                color: AppColors.primary,
                                                shape: BoxShape.circle,
                                              ),
                                            ),
                                        ],
                                      ),
                                      const SizedBox(height: 5),
                                      Text(
                                        item.description,
                                        style: const TextStyle(
                                          color: AppColors.textSecondary,
                                          fontSize: 12.5,
                                          height: 1.4,
                                        ),
                                      ),
                                      const SizedBox(height: 8),
                                      Text(
                                        item.time,
                                        style: const TextStyle(
                                          color: AppColors.textMuted,
                                          fontSize: 11,
                                          fontWeight: FontWeight.w500,
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ],
                            ),
                          ),
                        );
                      },
                    ),
            ),
          ],
        ),
      ),
    );
  }
}
